services:
  - type: web
    name: image-classification-api

    runtime: python

    plan: free

    region: singapore

    branch: main

    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn api.app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: APP_ENV
        value: production

      - key: DEBUG
        value: "False"

      - key: RELOAD
        value: "False"

      - key: HOST
        value: "0.0.0.0"

      - key: RENDER
        value: "True"

      - key: PORT
        sync: false